version: '2'
networks:
  bridge:
    driver: bridge

volumes:
  db:
    driver: anybox/buttervolume:latest
  data:
    driver: anybox/buttervolume:latest
  nginx:
    driver: anybox/buttervolume:latest

services:
  wiki:
    image: "xwiki:10.8.1-slim"
    # this ensures that we build 
    # the pre-built download does not support ARM
    build: 
      context: 10/tomcat
 #    context: https://github.com/keithy/xwiki-contrib.git#keithy:10/tomcat
      dockerfile: Dockerfile
      # BUILDTIME ENVIRONMENT
      args:
        DB: mysql
        XWIKI_VERSION: 10.8.1
        XWIKI_DOWNLOAD_SHA256: ed9436b5704e8cd4bc399c017f2ef7cf32e8f18f4e75a4fcc52782d933e9893c
    depends_on:
      - mariaDB
    ports:
      - "8080:8080"
    # RUNTIME ENV
    # The DB_USER/DB_PASSWORD/DB_HOST variables are used in the hibernate.cfg.xml file.
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_DATABASE=xwiki
#      - DB_HOST=mariaDB # use TCP/IP
      - DB_HOST=localhost # use socket
    # Provide a name instead of an auto-generated id for the xwiki permanent directory configured in the Dockerfile,
    # to make it simpler to identify in 'docker volume ls'.
    volumes:
      - data:/usr/local/xwiki
      - /run/mysqld:/run/mysqld # access socket available on the host
    networks:
      - bridge
    restart: always

# The container that runs MySQL/MariaDB

  mariaDB:
  # image: "mysql:5.7"
    image: "keithy/alpine-mariadb:armhf"
    build:
      context: https://github.com/keithy/alpine-mariadb.git#:alpine-mariadb-armhf
    # - Provide a name instead of an auto-generated id for the mysql data, to make it simpler to identify in
    # 'docker volume ls'
    volumes:
      - db:/var/lib/mysql
      - /run/mysqld:/run/mysqld # make the socket available on the host
    # Configure the MySQL database and create a user with provided name/password.
    # See https://hub.docker.com/_/mysql/ for more details.
    environment:
      - MYSQL_ROOT_PASSWORD=xwiki
      - MYSQL_USER=xwiki
      - MYSQL_PASSWORD=xwiki
      - MYSQL_DATABASE=xwiki
    ports:
      - "3306:3306"
    networks:
      - bridge
    command: 
      - --character-set-server=utf8 
      - --collation-server=utf8_bin
      - --explicit-defaults-for-timestamp=1
    restart: always

  # To use this client: docker-compose run --rm client
  client:
    image: yobasystems/alpine-mariadb:armhf
    container_name: mysql_CLI
    networks:
      - bridge
    volumes:
      - ./10/mysql-tomcat/mysql/xwiki.cnf:/etc/mysql/conf.d/xwiki.cnf
 #    - /run/mysqld:/run/mysqld # access the socket on the host
    depends_on:
      - mariaDB
    entrypoint:
      - mysql 
      - --user=root
      - --password=xwiki 
      - --host=mariaDB
      - --protocol=TCP
      - --default-character-set=utf8
      - xwiki

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - data:/usr/share/nginx/html:ro
      - nginx:/etc/nginx:ro
    networks:
      - bridge
    depends_on:
      - wiki
    restart: always



